networks:
  default:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
services:
  template:
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK}
      - traefik.tags=${TRAEFIK_TAGS}
      - traefik.http.middlewares.csr-ratelimit.ratelimit.average=20
      - traefik.http.middlewares.csr-ratelimit.ratelimit.burst=30
      - traefik.http.middlewares.csr-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=42
      - traefik.http.middlewares.csr-ratelimit.ratelimit.sourcecriterion.requesthost=true
      replicas: ${NUMBER_REPLICAS}
      restart_policy:
        condition: ${SERVICE_RESTART_CONDITION}
        delay: 10s
      update_config:
        delay: 30s
        parallelism: 1
    env_file: env_vars/${GO_STAGE_NAME}.env
    image: ${REGISTRY}/${IMAGETAG}:${GO_REVISION}
    networks:
    - default
    - traefik
version: '3.7'
